-- Add SEMI_ANNUAL to Plan enum
ALTER TYPE "Plan" ADD VALUE 'SEMI_ANNUAL';

-- Add new columns
ALTER TABLE "members" ADD COLUMN "first_name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "members" ADD COLUMN "last_name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "members" ADD COLUMN "date_of_birth" DATE;
ALTER TABLE "members" ADD COLUMN "member_number" INTEGER GENERATED BY DEFAULT AS IDENTITY;

-- Backfill first_name and last_name from full_name for existing rows
UPDATE "members"
SET
  "first_name" = split_part("full_name", ' ', 1),
  "last_name" = trim(substr("full_name", length(split_part("full_name", ' ', 1)) + 1));

-- Drop old full_name column
ALTER TABLE "members" DROP COLUMN "full_name";

-- Add unique constraint for member_number
ALTER TABLE "members" ADD CONSTRAINT "members_member_number_key" UNIQUE ("member_number");

-- Add index on member_number
CREATE INDEX "members_member_number_idx" ON "members"("member_number");
